version: '3.5'
services:
  springboot-docker-compose-mysql-app-container:
    image: springboot-docker-compose-mysql-app:latest
    container_name: springbootdockercontainer
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://192.168.99.100:3306/testdb?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=testuser
      - SPRING_DATASOURCE_PASSWORD=testuser@123
      - SPRING_PROFILES_ACTIVE=docker
    ports:
        - 8084:8084
    volumes:
      - /e/sudheer/stsworkspace/springdocker/tmp:/tmp
