version: '3'

services:
  mysql-standalone-container:
    image: mysql:5.7
    env_file: .env
    ports:
      - 3306:3306
    volumes:
      - ./../tps-db/data:/var/lib/mysql:rw
      - ./../tps-db/schema:/docker-entrypoint-initdb.d:ro
  springboot-docker-compose-mysql-app-container:
    image: springboot-docker-compose-mysql-app:1
    ports:
        - 8084:8084
    depends_on:
      - mysql-standalone-container
    volumes:
      - /data/springboot-docker-compose-mysql-app